/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 smoke.glb -d 
*/
import * as THREE from 'three';
import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';

export function Steam(props) {
  const {nodes, materials} = useGLTF('/models/studio12/smoke.glb');

  const material = new THREE.MeshBasicMaterial({
    color: 0x000000,
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.CoffeeSmoke.geometry}
        material={material}
        position={[2.494, 0.874, 0.5]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.131, 0.036, 0.036]}
        // scale={[1, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload('/models/studio12/smoke.glb');
